language: go
go:
  - 1.18.x
env:
  global:
    - GO111MODULE=on
cache:
  directories:
    - "$GOPATH/pkg/mod"
    - "$HOME/.cache/go-build"
services:
  - docker
install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow --tags; fi

jobs:
  include:
    - stage: publish
      name: publish images
      script:
        - make publish
