language: go
go:
  - 1.16.x
env:
  global:
    - GO111MODULE=on
cache:
  directories:
    - "$GOPATH/pkg/mod"
    - "$HOME/.cache/go-build"
install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow --tags; fi

jobs:
  include:
    - stage: test
      name: Go Test
      script:
        - make test

    - stage: publish
      name: Publish
      if: "env(TRAVIS_TAG) IS present"
      script:
        - make publish
